name: dev
variables:
  - name: base_url
    value: http://localhost:4000
  - name: users
    value: "{{base_url}}/users"
  - name: products
    value: "{{base_url}}/products"
  - name: orders
    value: "{{base_url}}/orders"
  - name: auth
    value: "{{base_url}}/auth"
  - secret: true
    name: token
  - name: permissions
    value: "{{base_url}}/permissions"
