info:
  name: products
  type: http
  seq: 1

http:
  method: GET
  url: "{{products}}?sort=name&page=1&page_size=3"
  params:
    - name: sort
      value: name
      type: query
    - name: page
      value: "1"
      type: query
    - name: page_size
      value: "3"
      type: query
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
